language: go

sudo: false

go:
  - "1.10"
  - "1.11"
  - tip

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -race -v -cover -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci

branches:
  only:
  - master
